apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: devops-excercise-autoscale
spec:
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  behavior:
    scaleDown:
      policies:
      - type: Percent
        value: 10
        periodSeconds: 30
      selectPolicy: Disabled # Disabled / Min / Max
      stabilizationWindowSeconds: 300
    scaleUp:
      policies:
      - type: Percent
        value: 75
        periodSeconds: 30
      selectPolicy: Disabled # Disabled / Min / Max
      stabilizationWindowSeconds: 0
